{
 "title": "Real-Time Crypto Ingestion Pipeline",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Real-Time Volatility Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Bitcoin (BTC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT\r\n  window_end AS \"time\",\r\n  avg_price AS \"Precio Promedio BTC\"\r\nFROM crypto_alerts\r\nWHERE symbol = 'BTC'\r\nORDER BY window_end ASC"
    }
   ]
  },
  {
   "title": "Ethereum (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT\r\n  window_end AS \"time\",\r\n  avg_price AS \"Precio Promedio ETH\"\r\nFROM crypto_alerts\r\nWHERE symbol = 'ETH'\r\nORDER BY window_end ASC"
    }
   ]
  },
  {
   "title": "Binance Coin (BNB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT\r\n  window_end AS \"time\",\r\n  avg_price AS \"Precio Promedio BNB\"\r\nFROM crypto_alerts\r\nWHERE symbol = 'BNB'\r\nORDER BY window_end ASC"
    }
   ]
  },
  {
   "title": "Solana (SOL)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT\r\n  window_end AS \"time\",\r\n  avg_price AS \"Precio Promedio SOL\"\r\nFROM crypto_alerts\r\nWHERE symbol = 'SOL'\r\nORDER BY window_end ASC"
    }
   ]
  },
  { "title": "Live Market Ticker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT window_end AS \"time\", avg_price, symbol\r\nFROM crypto_alerts\r\nORDER BY window_end ASC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "dataset": "crypto_db",
     "rawSql": "SELECT DISTINCT ON (window_end, symbol)\r\n  window_end AS \"time\",\r\n  avg_price,\r\n  symbol\r\nFROM crypto_alerts\r\n-- Filtramos por la moneda seleccionada en el dashboard o mostramos todas\r\nWHERE $__timeFilter(window_end)\r\nORDER BY window_end DESC, symbol, ingest_timestamp DESC"
    }
   ]
  }
 ]
}